### ISSUE TITLE
make ClockYou a default handler for time

### ISSUE THREAD

**Issue by basings** [Bnyro/ClockYou#106]
### Describe your suggested feature

# Problem

Time widgets like the widget from arcticons or breezy weather don't open ClockYou. Widgets will open other apps like GrapheneOS's clock or google's. You can't set ClockYou as default.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately that's not possible: Android uses the system clock app for that, and there's no way to change that as long as Clock You is not the system app pre-installed by the ROM.

**Comment by basings** [comment]
It works with simple clock as well. Google's clock is also not preinstalled on GrapheneOS.

**Comment by Bnyro** [comment]
I was able to figure out what BreezyWeather uses internally, however this might not work for every app, since some of them hardcode the clock app to use.
