### ISSUE TITLE
Analog Clock Widget is not Centered

### ISSUE THREAD

**Issue by IAGOnGithub** [Bnyro/ClockYou#109]
### Steps to reproduce

1. Create an analog clock widget
2. It aligns to the top left corner, not centering either horizontally or vertically

### Expected behavior

It should be centered both horizontally and vertically

### Actual behavior

It is not centered at all

### Clock You version

5.1

### Android version

Android 13

### Other details

On the Nova7 launcher

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a screenshot.

**Comment by IAGOnGithub** [comment]
![Screenshot_20230721_042543](https://github.com/Bnyro/ClockYou/assets/122576313/3f49584b-eeec-4a67-abc6-0901985828e0)
![Screenshot_20230721_042411](https://github.com/Bnyro/ClockYou/assets/122576313/c1ef1fd8-8b74-46c2-83a5-077c31401fe6)
Turns out, my original report was wrong. It isn't centered vertically either. I'll edit the bug report.
