### ISSUE TITLE
IzzyOnDroid

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/ClockYou#12]
### Describe your suggested feature

Hey @IzzySoft,

it would be great if you could help me out yet another time with approximately the last app from me for a while (unfortunately even my time is limited and I'll probably soon start struggling at maintaining all of the apps :upside_down_face: ).
Clock You is as the name already says, an app for watching the time, scheduling alarms, creating timers and using a stopwatch, apart from that it has some clock widgets inbuilt.
I'd be very happy to let other people find out about it via your app repository.

Have a good one
Cheers

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IzzySoft** [comment]
Thanks! Will be [there](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.clock) with the next sync.

And if you're looking for some nice feature 99% of all alarm clocks are missing: integrate a holiday calendar by allowing to add one or more `*.ics` to be fed locally (so you don't need to add `INTERNET`) plus maybe a possibility to add personal dates directly (for those who'd otherwise struggle with the ICS format) – et voila! That ugly "get-to-work" alert wakes you up each **work** day only, skipping that Easter-Friday and Easter-Monday (to pick something just currently running) to let you sleep in.

I really wonder why almost all clock apps lack this feature. And yours would be outstanding then as the only FOSS one having it (I just know about a single clock app having that feature, and that's not FOSS but even added trackers with its newer versions).

**Comment by IzzySoft** [comment]
PS: Let me know when you've addes text in your Fastlane tree :wink: (hint: it currently has screenshots only – no short-desc, full-desc, featureGraphic etc).

**Comment by Bnyro** [comment]
> PS: Let me know when you've addes text in your Fastlane tree wink (hint: it currently has screenshots only – no short-desc, full-desc, featureGraphic etc).
>
Oh damn, silly me.
I've been running `git add .` in the directory of the screenshots instead of the project's root folder, added now!

**Comment by Bnyro** [comment]
> Thanks! Will be [there](https://apt.izzysoft.de/fdroid/index/apk/com.bnyro.clock) with the next sync.
> 
Great, thank you!
> And if you're looking for some nice feature 99% of all alarm clocks are missing: integrate a holiday calendar by allowing to add one or more `*.ics` to be fed locally (so you don't need to add `INTERNET`) plus maybe a possibility to add personal dates directly (for those who'd otherwise struggle with the ICS format) – et voila! That ugly "get-to-work" alert wakes you up each **work** day only, skipping that Easter-Friday and Easter-Monday (to pick something just currently running) to let you sleep in.
> 
Oh well, that sounds very interesting. I'm not yet familiar with the ics format, but it sounds like quite a nice addition. I'll let you know when I've added support for it (if it's doable), but don't expect me to be too fast :joy:

**Comment by IzzySoft** [comment]
Fastlane: config updated here. :hankey: happens :rofl:

Holidays: would be really nice to have! I really wonder why not all alarm apps have that one way or the other. It's hopefully not too hard to figure and implement. Looking forward to that!

Btw, you didn't write what "sound sources" are considered by your alarm clock. Hope it's not just the "alarm sounds" of the device, but allows e.g. to pick a specific or random MP§ from the local collection as well. The only thing clear is it won't play any internet radio (no network permission). But maybe one could have start it a specific app as well? Thinking of the FM radio available with some devices. Though those usually need an antenna (which then is substituted by the cable of the headphones – which doesn't make much sense at bed time).

And if you like some crazy ideas (looking at the permissions requested to make sure none of them needs an extra one):

* snooze 1st time (max 5min) by just tap "snooze"
* snooze 2nd time: tap snooze exactly when it flashes (flash it max 5 times for 1s each)
* snooze 3rd time: same, but button moves around the screen
* snooze 4th time (you don't dare, do you?): like 3rd, but button now flashes a rhythm you need to repeat, turning up the volume each time
* snooze 5th time: hahaha, bet now you're awake anyway (or have the alarm turned off entirely)

Speaking of which: optionally, have turning off the alarm follow a similar pattern: once you hit the "off" button, it shows two new buttons in different position asking "are you sure" (one "yes", one "no"; play with colors and visibility; e.g. if "yes" was blue and "no" was red the first night, next night they have the colors reversed – or the question phrased opposite, like "keep it on") :see_no_evil:

To not drive folks nuts, name the entire schema "crazy mode" or something, and make it optional.

More funny ideas: if it can make use of the light sensor, ask the sleeper to send a morse "s" via the bed light to snooze, etc. :rofl:

**Comment by Bnyro** [comment]
> Btw, you didn't write what "sound sources" are considered by your alarm clock. Hope it's not just the "alarm sounds" of the device, but allows e.g. to pick a specific or random MP§ from the local collection as well. 
> 
Currently, there's no such option for customizing the alarm sound due to the early state of the app (it has basically been built in a single day). But of course, that's one of the next things that's going to be added!
> The only thing clear is it won't play any internet radio (no network permission). But maybe one could have start it a specific app as well? Thinking of the FM radio available with some devices. Though those usually need an antenna (which then is substituted by the cable of the headphones – which doesn't make much sense at bed time).
>
Yeah, I can't really come up with any app that could be started by an alarm. Most apps that intend to do something similar have it in-built themselves probably.
> And if you like some crazy ideas (looking at the permissions requested to make sure none of them needs an extra one):
> 
>     * snooze 1st time (max 5min) by just tap "snooze"
> 
>     * snooze 2nd time: tap snooze exactly when it flashes (flash it max 5 times for 1s each)
> 
>     * snooze 3rd time: same, but button moves around the screen
> 
>     * snooze 4th time (you don't dare, do you?): like 3rd, but button now flashes a rhythm you need to repeat, turning up the volume each time
> 
>     * snooze 5th time: hahaha, bet now you're awake anyway (or have the alarm turned off entirely)
> 
> 
Sounds like a funny idea, indeed! I really like enabling such things for all users the first april :joy:
> More funny ideas: if it can make use of the light sensor, ask the sleeper to send a morse "s" via the bed light to snooze, etc. rofl
>
It'd actually be very interesting how an app can interact with the light sensor without additional permissions, but that will probably nothing I'd consider adding an additional permission for :joy:

**Comment by IzzySoft** [comment]
> Currently, there's no such option for customizing the alarm sound due to the early state of the app (it has basically been built in a single day). But of course, that's one of the next things that's going to be added!

Yes, yes, totally clear – and glad you like my funny ideas! I was just collecting them to keep you on it :smile:

> Yeah, I can't really come up with any app that could be started by an alarm.

Any internet radio app? Any app that can play a stream – pre-configured or passed along? Any music app with its playlist? Any app that could forward your request to the coffee machine, so the smell of fresh coffee gets you out of bed? That's just what comes to mind immediately. Like with Tasker, advanced users could even set up their own "intent calls".

> Sounds like a funny idea, indeed! I really like enabling such things for all users the first april :joy:

Hehe, yes, that sounds like it, too :rofl:

> It'd actually be very interesting how an app can interact with the light sensor without additional permissions,

That was the idea. And I'd not be surprised if that wouldn't need any special permission at all. After all, auto-brightness makes use of it, too. For starters, how about [this](https://developer.android.com/guide/topics/sensors/sensors_environment) (taken from a quick search)?
