### ISSUE TITLE
Option for widget background transparency

### ISSUE THREAD

**Issue by ViktorKahu** [Bnyro/ClockYou#20]
### Describe your suggested feature

A hard option with a slider to set transparency percentage or an easier option to make a background on/off toggle. Or easy option #2 - to be able to pick a widget with a background or a different widget without a background.

### Other details

Would be greatly appreciated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't currently have plans to let users customize the appearance of widgets as they wouldn't go well with Material Design 3 anymore that way.

**Comment by ViktorKahu** [comment]
I meant something like this (see screenshot below), this is the way Google implement it, and it does not conflict with material you principles.

They give you a simple choice - background or no background.

But offcourse its up to you.

![Uploading Screenshot_20230411-212607.png…]()

**Comment by ViktorKahu** [comment]
I meant something like this (see screenshot below), this is the way Google implement it, and it does not conflict with material you principles.

They give you a simple choice - background or no background.

But offcourse its up to you.

![Screenshot_20230411-212607](https://user-images.githubusercontent.com/125934998/231150328-dfc255fa-5f04-45c6-b416-2ab5a3840361.png)
