### ISSUE TITLE
Replace edit button with add button

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/ClockYou#21]
### Describe your suggested feature

I think it would be better if instead of pencil icon here will be "+" icon
![](https://user-images.githubusercontent.com/113282550/230959908-8c7e1624-be5e-4a79-af22-229e23048be0.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Rodrifer** [comment]
I think the best icon to indicate that something is being added is the "Add" icon.

![image](https://user-images.githubusercontent.com/126223/234460821-14d238ec-7527-4a6f-910a-62666f6b94c3.png)

The problem I see is that the "Create" icon is exactly the same as the "Edit" icon and that can confuse the end user. We are saying that we are going to edit something when the action is to add.

I think @HotarunIchijou  is right, at least in the Alarm section.
