### ISSUE TITLE
[Bug] App crashes when stopping timer

### ISSUE THREAD

**Issue by pabloscloud** [Bnyro/ClockYou#22]
### Steps to reproduce

1. Create timer of below 5 seconds for example
2. Let it go to 0 sec
3. Press stop

### Expected behavior

The timer stops and the screen to set a timer shows up again

### Actual behavior

The app crashes sometimes and other times nothing happens

### Clock You version

2.0

### Android version

13

### Other details

CalyxOS 4.7.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in debug builds!
