### ISSUE TITLE
[Bug] Alarm sound for timers don't work

### ISSUE THREAD

**Issue by pabloscloud** [Bnyro/ClockYou#28]
### Steps to reproduce

1. Open timers tab
2. Set it to a sec
3. Press the start button
4. Wait for the timer to end

### Expected behavior

Alarm goes of

### Actual behavior

Just goes back to the setup screen for a new timer

### Clock You version

2.1

### Android version

13

### Other details

CalyxOS 4.7.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Did you make sure to enable notifications for the app?

**Comment by pabloscloud** [comment]
First of, the app didn't request them.

Now that I enabled them, its just a notification with the default notification sound.

Not quite alarming.

**Comment by Bnyro** [comment]
But it works as expected then.

**Comment by pabloscloud** [comment]
No, it's not an alarm. It's a notification.
