### ISSUE TITLE
enhancement: add "turn off" and "sleep" to alarms

### ISSUE THREAD

**Issue by qube-03** [Bnyro/ClockYou#29]
hi, ive actually got two things, one is a minor inconvenience and the other is in the title

1. the typical material you create icon in the bottom right corner blocks some elements, especially on the alarms page when you have a lot of alarms, is a bit fiddely when you wanna edit your latest one

2. add a "turn off" (i mean skipping the alarm once, not actually completely turning it off) and a "sleep" button for alarms, probably in the notification, pretty self explanatory why theyre useful

thank you!

**Comment by qube-03** [comment]
it boils down to this:
- the button in the bottom right hides things
- add a skip once button in the notification for alarms

**Comment by qube-03** [comment]
the button is only an issue with the bottom most entries, so my solution would be to just let the user scroll a bit further down so nothing is behind the button but above it instead

**Comment by Bnyro** [comment]
I don't really get the "skip once" button. It's just a button in the notification that stops the current alarm from ringing?

**Comment by Bnyro** [comment]
Ah, got you. However, I currently do not plan adding something like this since I don't think it'd be too useful and it's easy enough to manually disable and later re-enable the alarm.

**Comment by qube-03** [comment]
i respect you dont wanna add the feature, i still do agree with serrq tho, its very convenient to have so you dont forget to turn your alarm back on
