### ISSUE TITLE
option to start the week at Monday / other days

### ISSUE THREAD

**Issue by KurumiFake** [Bnyro/ClockYou#32]
### Describe your suggested feature

an option somewhere in the app that allows the user to change the starting day of the week

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No plans for that, it wouldn't really change anything in the user experience.

**Comment by eandersons** [comment]
> No plans for that, it wouldn't really change anything in the user experience.

It really changes the user experience. At first it is a bit confusing for those that are used to weeks starting with Monday.
Following your logic showing AM/PM also should not change anything in the user experience as everyone (or at least most of people) understands 24 hour format and it really does not change the behaviour of  alarms, but it was recently implemented (#221).
