### ISSUE TITLE
Alarm time is incorrect

### ISSUE THREAD

**Issue by muznyo** [Bnyro/ClockYou#38]
### Steps to reproduce

1. Set an alarm, for example 00:01
2. When created, it shows up as 01:00

### Expected behavior

It should show correct time.

### Actual behavior

It doesn't show correct time

![Screenshot_20230413-201708_Clock You](https://user-images.githubusercontent.com/24987471/231848695-fb55ea89-144a-458b-8a8b-18300904b657.png)

![Screenshot_20230413-201711_Clock You](https://user-images.githubusercontent.com/24987471/231848707-b32ec118-f4ac-4595-a98c-70812ce740d4.png)

### Clock You version

3.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Fyi, the time is set correctly, it just doesn't show accurately.

**Comment by Bnyro** [comment]
So the alarm should ring at the time you have set it too.
