### ISSUE TITLE
Delete alarm

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/ClockYou#39]
### Describe your suggested feature

I don't know why this feature isn't here yet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Swipe to the right.

**Comment by HotarunIchijou** [comment]
But why there's no button for this?

**Comment by Bnyro** [comment]
Simplement car il n'est pas necessaire.
