### ISSUE TITLE
alarm doesn't trigger

### ISSUE THREAD

**Issue by itsmmt305** [Bnyro/ClockYou#5]
### Steps to reproduce

set a time for the alarm to buzz
tap the turn on switch

### Expected behavior

the app should show a toast telling alarm has been set for so and so time

### Actual behavior

app crashes

### Clock You version

v1.0

### Android version

Android 12 / MIUI 13

### Other details

i thought there might be problems with the alarm not going off and that'd be well permissible in the first release but i cant even set the alarm time. sorry if i come across as jumping the gun here.
although the clocks, timer and stopwatch work fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, that's very weird.
The issue has been that alarms didn't fire at the correct times, however that's being fixed with the latest release.
I didn't yet face any issues in terms of that, either a crash log or a screen recording would be very helpful!

**Comment by itsmmt305** [comment]
https://user-images.githubusercontent.com/94820934/230767844-21b6ac28-9842-4b61-93e2-c3e75fd33717.mp4


https://user-images.githubusercontent.com/94820934/230767847-6e7ccef3-4b37-4ba3-b3ff-48e923999ec6.mp4



what doing here which is not visible here is im turning the switch on. thats when its crashing
its still v1.0

**Comment by Bnyro** [comment]
Have you enabled notifications for the app? These are required in order for the alarm to work!

**Comment by itsmmt305** [comment]
yeah they were.. im using android 12.

show on lock screen, display popup window in background all of it's enabled

**Comment by itsmmt305** [comment]
its working fine now.. idk how but its workin. at the right time too.
