### ISSUE TITLE
Adding app version and app channel info in CY

### ISSUE THREAD

**Issue by serrq** [Bnyro/ClockYou#51]
I would like see more easily informations about version and channel about ClockYou development.

For example:
ClockYou 3.1 Github
or
ClockYou 3.1 F-droid (via IzzyOnDroid)

This is useful to track future bugs, issues, or simply to know what one has installed.

**Comment by Bnyro** [comment]
The apks installed from the IzzyOnDroid repo and GitHub are exactly the same, therefore differentiating here is not possible.
