### ISSUE TITLE
Some BRICS cities are not present in the general list

### ISSUE THREAD

**Issue by serrq** [Bnyro/ClockYou#52]
I cannot find Brazilia (Brazil), Beijing (China), New Delhi (India), Pretoria (South Africa) time cards.

I find it disconcerting to put Moscow as a European city.

Does the API provider play toy soldiers and annex territories to its military block?

**Comment by Bnyro** [comment]
We're using the official Android system API, so the time zones visible are the ones the Android developers seem to consider as important. It might be possible that they didn't update it in a while, however I'm not aware of any better way to get a list of time zones.
