### ISSUE TITLE
Add GitHub link to the app (like Record You app)

### ISSUE THREAD

**Issue by xmha97** [Bnyro/ClockYou#57]
### Describe your suggested feature

![Screenshot_2023-04-25-23-30-03-495_com bnyro recorder](https://user-images.githubusercontent.com/23485114/234389526-68f624b9-4efb-406d-81c3-cb06293f998c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already added in debug builds earlier.
