### ISSUE TITLE
AppShortcut

### ISSUE THREAD

**Issue by xmha97** [Bnyro/ClockYou#58]
### Describe your suggested feature

Please add the AppShortcut like Xiaomi clock app.

![Screenshot_2023-04-25-23-28-17-434_com miui home](https://user-images.githubusercontent.com/23485114/234389857-d4d4bf6c-c859-4006-9dfb-3361bb0d102d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I currently don't plan adding shortcuts.
