### ISSUE TITLE
Change Icon and text when no Alarm exist

### ISSUE THREAD

**Issue by Rodrifer** [Bnyro/ClockYou#59]
### Describe your suggested feature

To improve the end-user interaction, I propose to change the icon and the text when there are no alarms.

For example:

![image](https://user-images.githubusercontent.com/126223/234929494-abdd2521-55a0-40bb-80fb-7267b19b2e4a.png)

The current icon "Layers" does not give any clear message about what should be in that place and the text is vague.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for the suggestion!
However, I currently don't see a reason to change it. It should be self explaining that the reference is to alarms in regards of the top bar title and navigation bar section, apart from that the `Nothing here` label can be reused in other parts of the app which makes it less work for translators.
