### ISSUE TITLE
Alarms don't work at all

### ISSUE THREAD

**Issue by pasqchia** [Bnyro/ClockYou#65]
### Steps to reproduce

1. Setting up an alarm.

### Expected behavior

The alarm should ring at the hour I've set it.

### Actual behavior

The alarm doesn't ring at all. The app has all of the needed permissions, I've set "Battery Usage" to "Unrestricted", I've tried both with the phone locked and unlocked, yet, doesn't seem to work in neither ways. Simple Clock seems to work, so it's not an OS' related issue. This issue persists on both 12-hour and 24-hour time.

### Clock You version

3.1

### Android version

ArrowOS 13.0 (Android 13)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
#33, and notifications have to be allowed.
