### ISSUE TITLE
Change the buttons

### ISSUE THREAD

**Issue by HotarunIchijou** [Bnyro/ClockYou#7]
### Describe your suggested feature

Buttons are small and it's hard to click. So I think it would be better if buttons will be in the middle and use [md.sys.color.primary](https://m3.material.io/m3/pages/using-color/tokens#7fd4440e-986d-443f-8b3a-4933bff16646)  as an unselected button color

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I don't currently plan any changes in regards of that.
