### ISSUE TITLE
Delete alarms

### ISSUE THREAD

**Issue by unityastronaut** [Bnyro/ClockYou#73]
### Describe your suggested feature

Unused alarms cannot be deleted. (Except by clearing app storage)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Swipe the alarm to the right.
