### ISSUE TITLE
Add support for dynamicSpot

### ISSUE THREAD

**Issue by Myzel394** [Bnyro/ClockYou#76]
### Describe your suggested feature

[dynamicSpot](https://play.google.com/store/apps/details?id=com.jamworks.dynamicspot&pli=1) is an app that allows Android users to create a Dynamic Island.

Using the native Google Clock, dynamicSpot works flawlessly, but with Clock You it doesn't.

Here's an example video:

[out.webm](https://github.com/Bnyro/ClockYou/assets/50424412/187812cb-8dbb-41d9-a5ae-2549c8026aa6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
Btw, LibreTube does work with dynamicSpot

**Comment by Bnyro** [comment]
Hmm, I might have an idea for that

**Comment by Bnyro** [comment]
Please test a build from https://github.com/Bnyro/ClockYou/commit/318cd69fd31cfd44310e0972ad66b631548987e0, I'm confident that worked out.

**Comment by Myzel394** [comment]
I'm sorry, but unfortunately it's still not working :/

I just realized that the Google Clock shows the timer duration (and also stopwatch btw) in real time in the notifications, while Clock You doesn't. How about we add the current remaining time (and stopwatch time) into the notification as well? Not only could this close this issue, but it's also much more useful in my opinion.

![20230621_201704_temp](https://github.com/Bnyro/ClockYou/assets/50424412/b2de8662-9229-49a6-8287-4e6efd4501c1)

**Comment by Bnyro** [comment]
We did so before the commit. Doesn't it show in the stopwatch either?

**Comment by Bnyro** [comment]
And have you tested whether any other clock app on F-Droid works properly? (E.g. SimpleClock or https://www.f-droid.org/packages/com.best.deskclock/)

**Comment by Myzel394** [comment]
@Bnyro I just tried SimpleClock and it **does not work**. So I guess DynamicSpot then probably has native support for Google's clock, what do you think?

**Comment by Bnyro** [comment]
Could you please try the desk clock too? It's almost the AOSP one (official one delivered by Google). If that doesn't work, there's no way we can add support for it.

**Comment by Myzel394** [comment]
It **did not work**. I'll write the developer an email asking if they provide some way to add support for it then. Thanks for your help though :D
