### ISSUE TITLE
Publish app on Fdroid

### ISSUE THREAD

**Issue by chromer030** [Bnyro/ClockYou#80]
### Describe your suggested feature

Hey, thanks for app, please publish it on Fdroid, so more user be able to find and use it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Starcr0ss** [comment]
I would just like to let you know, the app can be installed through an F-Droid client if you have the IzzyOnDroid repo set up! :)

**Comment by chromer030** [comment]
OK then, thanks.

**Comment by julianfairfax** [comment]
@Bnyro do I have your permission to [add this app as well as Connect You](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13386) to the main F-Droid repo, in order to complete your suite of apps on there? Like Record You, I won't expect you to deal with F-Droid in any way (if builds fail etc.), just the apps will be there for easier access to those who want them. Thanks!

**Comment by Bnyro** [comment]
> @Bnyro do I have your permission to [add this app as well as Connect You](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13386) to the main F-Droid repo, in order to complete your suite of apps on there? Like Record You, I won't expect you to deal with F-Droid in any way (if builds fail etc.), just the apps will be there for easier access to those who want them. Thanks!
>
Yes, I'd be okay with that. Thanks for your efforts!

**Comment by Bnyro** [comment]
Though Wall You would still be missing in order to have all apps published on F-Droid, adding it as well might be the best for user convenience in the end. I can do that myself if you don't like to, otherwise I'd appreciate it being added as well :)

**Comment by julianfairfax** [comment]
> Though Wall You would still be missing in order to have all apps published on F-Droid, adding it as well might be the best for user convenience in the end. I can do that myself if you don't like to, otherwise I'd appreciate it being added as well :)

I will do that (probably in a few hours), in a separate pull request. But it should be relatively easy to do as well, so you can if you want it as soon as possible.

**Comment by Bnyro** [comment]
If you could open a PR in the next few days, that would be great. Thank you!

**Comment by julianfairfax** [comment]
> If you could open a PR in the next few days, that would be great. Thank you!

I opened one, but the build is failing: https://gitlab.com/julianfairfax/fdroiddata/-/jobs/4690235134. Seems to be something with the reproducible builds.

The manifest is just a copy of the same template used for all your other apps: https://gitlab.com/fdroid/fdroiddata/-/blob/4b03c23092a659d66d9b8f5e08c20ebb732f3fd4/metadata/com.bnyro.wallpaper.yml.

**Comment by Bnyro** [comment]
Hmm, I'll take a look tomorrow

**Comment by IzzySoft** [comment]
Btw, no notes on my end on whether the app shall stay in my repo, now that it is on F-Droid? My badge is not on the Readme, so I assume I shall remove it here then, @Bnyro?

**Comment by Bnyro** [comment]
Yes, it's okay for me to only have it on F-Droid now. Thank you for keeping the app in your repo for so long! <3

**Comment by IzzySoft** [comment]
Thanks! Then I remove it. Gladly kept it, and still have kept it if you'd wanted – but with most of the other apps already "moved" it makes sense this way.
