### ISSUE TITLE
Timer keypad does not allow full entry with 1,2, and 3 buttons

### ISSUE THREAD

**Issue by Starcr0ss** [Bnyro/ClockYou#81]
### Steps to reproduce
Scenario 1:
1. Press 1
2. Press another number
3. Maximum allowed time is 1 second

Scenario 2:
1. Press 2
2. Press any 2 numbers after that
3. Hits a wall once the initial 2 hits the first minutes position (Ex: 2m 23s)

Scenario 3:
1. Press 3
2. Press any 4 numbers after that
3. Hits a wall once the initial 3 hits the first hours position (Ex: 3h21m05s)

### Expected behavior

I should be able to type in any number I want without hitting "walls" in entry. 

### Actual behavior

I cannot type in entries that use the full duration available unless the starting number is a 4-9.

### Clock You version

5.0 (7)

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Myzel394** [comment]
I figured out that if you repeatedly press the delete button, it works. I think the issue is caused by the initial state

**Comment by Myzel394** [comment]
yes can confirm that's the issue, I fix it quickly and open a PR then
