### ISSUE TITLE
Number Keypad not working

### ISSUE THREAD

**Issue by Myzel394** [Bnyro/ClockYou#83]
### Steps to reproduce

Use new number keypad

### Expected behavior

Should work

### Actual behavior

Not working

### Clock You version

5.0

### Android version

Android 13

### Other details

Not sure what happened there, because it was working fine before I pushed the last commit, but maybe I changed something accidentally. I'm looking into this and will open a PR

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It sometimes does work (that's why I didn't find an issue either when testing), see #81
