### ISSUE TITLE
Slightly reduce the size of the number keypad

### ISSUE THREAD

**Issue by Artem13327** [Bnyro/ClockYou#92]
### Describe your suggested feature

Slightly reduce the size of the digital keypad. This is needed to fix it
![1](https://github.com/Bnyro/ClockYou/assets/68551925/9dfda9dd-21c2-44ac-8d89-71595774265e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by unityastronaut** [comment]
I think this is because of the 3-button navigation. It's pushing the navigation bar and floating action button further up. This is not present with gesture navigation turned on.
